version: '2'

services:

  zammad-backup:
    command: ["zammad-backup"]
    depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    build:
      context: ./containers/zammad-postgresql/
      dockerfile: Dockerfile
    links:
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-data:/opt/zammad
    environment:
      - RAILS_ENV


  zammad-elasticsearch:
    build:
      context: ./containers/zammad-elasticsearch
      dockerfile: Dockerfile
    restart: ${RESTART}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zammad-init:
    command: ["zammad-init"]
    depends_on:
      - zammad-postgresql
    build:
      context: ./containers/zammad
      dockerfile: Dockerfile
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: on-failure
    volumes:
      - zammad-data:/opt/zammad
    environment:
      - RAILS_ENV

  zammad-memcached:
    command: ["zammad-memcached"]
    build:
      context: ./containers/zammad-memcached
      dockerfile: Dockerfile
    restart: ${RESTART}

  zammad-nginx:
    command: ["zammad-nginx"]
    depends_on:
      - zammad-railsserver
    build:
      context: ./containers/zammad
      dockerfile: Dockerfile
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    expose:
      - 80
    environment:
      - RAILS_ENV

  zammad-postgresql:
    build:
      context: ./containers/zammad-postgresql
      dockerfile: Dockerfile
    restart: ${RESTART}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - RAILS_ENV

  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
    build:
      context: ./containers/zammad
      dockerfile: Dockerfile
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    environment:
      - RAILS_ENV
    expose:
      - 3000

  zammad-scheduler:
    command: ["zammad-scheduler"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    build:
      context: ./containers/zammad
      dockerfile: Dockerfile
    links:
      - zammad-elasticsearch
      - zammad-memcached
      - zammad-postgresql
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    environment:
      - RAILS_ENV

  zammad-websocket:
    command: ["zammad-websocket"]
    depends_on:
      - zammad-memcached
      - zammad-railsserver
    build:
      context: ./containers/zammad
      dockerfile: Dockerfile
    links:
      - zammad-postgresql
      - zammad-memcached
    restart: ${RESTART}
    volumes:
      - zammad-data:/opt/zammad
    environment:
      - RAILS_ENV

volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-data:
    driver: local
